# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smstwilio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
